spring:
  datasource:
    url: jdbc:h2:mem:jikgwan;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  # Redis 설정 (선택적 - 없어도 앱 실행됨)
  # 로컬에서 Redis를 사용하려면: docker run -d -p 6379:6379 redis:alpine
  # data:
  #   redis:
  #     host: localhost
  #     port: 6379

jwt:
  secret: jikgwan-local-secret-key-for-development-only
  access-token-validity: 3600000  # 1시간
  refresh-token-validity: 604800000  # 7일

storage:
  type: local
  local:
    base-path: ./uploads

logging:
  level:
    root: INFO
    com.jikgwan: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
