spring:
  application:
    name: jikgwan-api

  datasource:
    url: jdbc:mysql://localhost:3306/jikgwan?useUnicode=true&characterEncoding=utf8
    username: ${DB_USERNAME:jikgwan_user}
    password: ${DB_PASSWORD:jikgwan_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 50
    show-sql: false
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: ${JWT_SECRET:jikgwan-secret-key-for-development-only-change-in-production}
  access-token-validity: 3600000  # 1시간
  refresh-token-validity: 604800000  # 7일

aws:
  s3:
    bucket: ${S3_BUCKET:jikgwan-profiles}
    region: ${AWS_REGION:ap-northeast-2}

storage:
  type: ${STORAGE_TYPE:local}  # local or s3
  local:
    base-path: ${LOCAL_STORAGE_PATH:./uploads}

logging:
  level:
    root: INFO
    com.jikgwan: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
